### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MarcusCS** [cmatthewbrooks/r2kit#10]
![issue](https://user-images.githubusercontent.com/44235326/47093178-47444400-d246-11e8-9cb7-0c5e5e89362b.png)

**Comment by cmatthewbrooks** [comment]
That should have been fixed in early September the day before r2con started. When did you pull this repo and what version of r2 are you using?

**Comment by cmatthewbrooks** [comment]
Actually, that's different than what was fixed in e72717bff07eee31453c035b84d991b93faa9825 but I don't get the same error using the latest r2 from git and the most recent version of this repo.

Is your r2 up to date?

**Comment by MarcusCS** [comment]
I was using the old version of r2.Fixed it,works perfectly now! Thanks..
