### ISSUE TITLE
r2.cmd -> r2.cmdj

### ISSUE THREAD

**Issue by Maijin** [cmatthewbrooks/r2kit#2]
https://github.com/cmatthewbrooks/r2kit/blob/e301720be8972b8a28e4b2831a6e4dff81024155/r2utils.py#L55

All the json commands should use r2.cmdj and not r2.cmd, r2.cmdj returns proper python dictionnary without need of manual parsing which is prone to error and ineficient.

**Comment by cmatthewbrooks** [comment]
Ah that's incredibly helpful. Thanks for the tip.

**Comment by cmatthewbrooks** [comment]
This should all be fixed now, as of 37982712eaad98811f1a80e78751b2c4d722c539.
